-- Sayeed Courses live backend foundation v2
-- Idempotent: safe to re-run after the first setup.

create table if not exists public.course_catalogue (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  educator text,
  price numeric(10,2) default 0,
  thumbnail_url text,
  telegram_url text,
  initial_likes bigint not null default 0,
  initial_dislikes bigint not null default 0,
  created_at timestamptz default now()
);

create table if not exists public.course_reactions (
  course_id bigint not null references public.course_catalogue(id) on delete cascade,
  session_id text not null,
  reaction text not null check (reaction in ('like','dislike')),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (course_id, session_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  type text default 'info',
  created_at timestamptz default now()
);

create table if not exists public.course_reaction_totals (
  course_id bigint primary key references public.course_catalogue(id) on delete cascade,
  likes bigint not null default 0,
  dislikes bigint not null default 0,
  updated_at timestamptz default now()
);

alter table public.course_catalogue enable row level security;
alter table public.course_reactions enable row level security;
alter table public.notifications enable row level security;
alter table public.course_reaction_totals enable row level security;

drop policy if exists "public read course catalogue" on public.course_catalogue;
create policy "public read course catalogue" on public.course_catalogue for select to anon using (true);

drop policy if exists "public read notifications" on public.notifications;
create policy "public read notifications" on public.notifications for select to anon using (true);

drop policy if exists "public read reaction totals" on public.course_reaction_totals;
create policy "public read reaction totals" on public.course_reaction_totals for select to anon using (true);

-- Seed the same 24 foundation courses currently rendered by the UI.
insert into public.course_catalogue (id,title,category,educator,price,thumbnail_url,telegram_url,initial_likes,initial_dislikes)
values
  (1, 'Alpha Batch 3.0', 'Coding & Tech', 'Sayeed Academy', 299, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (2, 'Complete DSA Batch', 'AI & Automation', 'Elite Faculty', 199, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (3, 'AI Automation Mastery', 'Finance & Taxation', 'Pro Learning', 399, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (4, 'Personal Growth Blueprint', 'Personal Growth & Mindset', 'Master Teachers', 249, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (5, 'Alpha Batch 3.0', 'Coding & Tech', 'Sayeed Academy', 299, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (6, 'Complete DSA Batch', 'AI & Automation', 'Elite Faculty', 199, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (7, 'AI Automation Mastery', 'Finance & Taxation', 'Pro Learning', 399, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (8, 'Personal Growth Blueprint', 'Personal Growth & Mindset', 'Master Teachers', 249, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (9, 'Alpha Batch 3.0', 'Coding & Tech', 'Sayeed Academy', 299, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (10, 'Complete DSA Batch', 'AI & Automation', 'Elite Faculty', 199, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (11, 'AI Automation Mastery', 'Finance & Taxation', 'Pro Learning', 399, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (12, 'Personal Growth Blueprint', 'Personal Growth & Mindset', 'Master Teachers', 249, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (13, 'Alpha Batch 3.0', 'Coding & Tech', 'Sayeed Academy', 299, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (14, 'Complete DSA Batch', 'AI & Automation', 'Elite Faculty', 199, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (15, 'AI Automation Mastery', 'Finance & Taxation', 'Pro Learning', 399, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (16, 'Personal Growth Blueprint', 'Personal Growth & Mindset', 'Master Teachers', 249, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (17, 'Alpha Batch 3.0', 'Coding & Tech', 'Sayeed Academy', 299, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (18, 'Complete DSA Batch', 'AI & Automation', 'Elite Faculty', 199, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (19, 'AI Automation Mastery', 'Finance & Taxation', 'Pro Learning', 399, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (20, 'Personal Growth Blueprint', 'Personal Growth & Mindset', 'Master Teachers', 249, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (21, 'Alpha Batch 3.0', 'Coding & Tech', 'Sayeed Academy', 299, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (22, 'Complete DSA Batch', 'AI & Automation', 'Elite Faculty', 199, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (23, 'AI Automation Mastery', 'Finance & Taxation', 'Pro Learning', 399, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0),
  (24, 'Personal Growth Blueprint', 'Personal Growth & Mindset', 'Master Teachers', 249, NULL, 'https://t.me/LWS_SPECIAL_SUPPORTS', 0, 0)
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.course_catalogue','id'),
  greatest(coalesce((select max(id) from public.course_catalogue), 1), 1),
  true
);

-- Backfill totals only for courses that don't have a totals row yet.
insert into public.course_reaction_totals(course_id,likes,dislikes)
select c.id,
       c.initial_likes + count(*) filter (where r.reaction='like'),
       c.initial_dislikes + count(*) filter (where r.reaction='dislike')
from public.course_catalogue c
left join public.course_reactions r on r.course_id=c.id
where not exists (select 1 from public.course_reaction_totals t where t.course_id=c.id)
group by c.id,c.initial_likes,c.initial_dislikes;

create or replace function public.ensure_course_reaction_total()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.course_reaction_totals(course_id,likes,dislikes)
  values (new.id,new.initial_likes,new.initial_dislikes)
  on conflict (course_id) do nothing;
  return new;
end;
$$;

drop trigger if exists trg_course_reaction_total on public.course_catalogue;
create trigger trg_course_reaction_total
after insert on public.course_catalogue
for each row execute function public.ensure_course_reaction_total();

create or replace function public.get_course_count()
returns bigint
language sql
security definer
set search_path = public
as $$ select count(*)::bigint from public.course_catalogue; $$;

grant execute on function public.get_course_count() to anon;

drop function if exists public.get_course_reaction_counts(bigint[]);
drop function if exists public.get_course_reaction_counts(bigint[],text);
create or replace function public.get_course_reaction_counts(course_ids bigint[], p_session_id text)
returns table(course_id bigint, likes bigint, dislikes bigint, user_reaction text)
language sql
security definer
set search_path = public
as $$
  select t.course_id,
         t.likes,
         t.dislikes,
         (select r.reaction from public.course_reactions r where r.course_id=t.course_id and r.session_id=p_session_id)
  from public.course_reaction_totals t
  where t.course_id = any(course_ids)
  order by t.course_id;
$$;

grant execute on function public.get_course_reaction_counts(bigint[], text) to anon;

create or replace function public.set_course_reaction(
  p_course_id bigint,
  p_session_id text,
  p_reaction text
)
returns table(course_id bigint, likes bigint, dislikes bigint, user_reaction text)
language plpgsql
security definer
set search_path = public
as $$
declare
  old_reaction text;
  new_likes bigint;
  new_dislikes bigint;
begin
  if p_reaction not in ('like','dislike') then raise exception 'invalid reaction'; end if;
  if length(p_session_id) < 12 or length(p_session_id) > 120 then raise exception 'invalid session'; end if;
  if not exists (select 1 from public.course_catalogue where id=p_course_id) then raise exception 'course not found'; end if;

  select reaction into old_reaction
  from public.course_reactions
  where course_id=p_course_id and session_id=p_session_id;

  if old_reaction = p_reaction then
    delete from public.course_reactions where course_id=p_course_id and session_id=p_session_id;
    update public.course_reaction_totals
      set likes = case when p_reaction='like' then greatest(likes-1,0) else likes end,
          dislikes = case when p_reaction='dislike' then greatest(dislikes-1,0) else dislikes end,
          updated_at=now()
      where course_id=p_course_id;
  else
    insert into public.course_reactions(course_id,session_id,reaction,updated_at)
    values(p_course_id,p_session_id,p_reaction,now())
    on conflict(course_id,session_id)
    do update set reaction=excluded.reaction,updated_at=now();

    update public.course_reaction_totals
      set likes = greatest(likes
          + case when p_reaction='like' then 1 else 0 end
          - case when old_reaction='like' then 1 else 0 end,0),
          dislikes = greatest(dislikes
          + case when p_reaction='dislike' then 1 else 0 end
          - case when old_reaction='dislike' then 1 else 0 end,0),
          updated_at=now()
      where course_id=p_course_id;
  end if;

  select likes,dislikes into new_likes,new_dislikes
  from public.course_reaction_totals
  where course_id=p_course_id;

  return query select p_course_id,new_likes,new_dislikes,
    (select r.reaction from public.course_reactions r where r.course_id=p_course_id and r.session_id=p_session_id);
end;
$$;

grant execute on function public.set_course_reaction(bigint,text,text) to anon;

insert into public.notifications(title,body,type)
select 'Welcome to Sayeed Courses','New course updates and important announcements will appear here.','info'
where not exists (select 1 from public.notifications);

-- Enable Realtime for safe aggregate rows, catalogue changes and notifications.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='course_reaction_totals') then
    execute 'alter publication supabase_realtime add table public.course_reaction_totals';
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='course_catalogue') then
    execute 'alter publication supabase_realtime add table public.course_catalogue';
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='notifications') then
    execute 'alter publication supabase_realtime add table public.notifications';
  end if;
exception when undefined_object then
  null;
end;
$$;
