-- Sayeed Courses — live catalogue, reactions, notifications and coupons.
-- Run this entire file in Supabase SQL Editor.
-- Safe to run again: additive changes + create-or-replace/drop patterns are used.

create table if not exists public.course_catalogue (
  id bigint generated by default as identity primary key,
  number integer,
  title text not null,
  category text not null,
  educator text,
  price numeric(10,2) default 0,
  rating numeric(3,2) default 4.50,
  reviews bigint not null default 0,
  thumbnail_url text,
  telegram_url text,
  initial_likes bigint not null default 0,
  initial_dislikes bigint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now()
);

alter table public.course_catalogue add column if not exists number integer;
alter table public.course_catalogue add column if not exists rating numeric(3,2) default 4.50;
alter table public.course_catalogue add column if not exists reviews bigint not null default 0;
alter table public.course_catalogue add column if not exists is_active boolean not null default true;

update public.course_catalogue
set number = id::integer
where number is null;

create unique index if not exists course_catalogue_number_uidx on public.course_catalogue(number);

create table if not exists public.course_reactions (
  course_id bigint not null references public.course_catalogue(id) on delete cascade,
  session_id text not null,
  reaction text not null check (reaction in ('like','dislike')),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (course_id, session_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  type text default 'info',
  created_at timestamptz default now()
);

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_percent numeric(5,2) not null check (discount_percent > 0 and discount_percent <= 100),
  starts_at timestamptz default now(),
  expires_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.course_catalogue enable row level security;
alter table public.course_reactions enable row level security;
alter table public.notifications enable row level security;
alter table public.coupons enable row level security;

drop policy if exists "public read course catalogue" on public.course_catalogue;
create policy "public read course catalogue" on public.course_catalogue for select to anon using (is_active = true);

drop policy if exists "public read notifications" on public.notifications;
create policy "public read notifications" on public.notifications for select to anon using (true);

-- Coupons are intentionally NOT publicly selectable or writable.
-- Project admins/owners create and expire them in Supabase Table Editor for now.
-- Future admin-panel access can use the same table with an admin JWT claim.

drop policy if exists "admin manage coupons" on public.coupons;
create policy "admin manage coupons" on public.coupons
for all to authenticated
using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop function if exists public.get_course_count();
create or replace function public.get_course_count()
returns bigint
language sql
security definer
set search_path = public
as $$ select count(*) from public.course_catalogue where is_active = true; $$;
grant execute on function public.get_course_count() to anon;

drop function if exists public.get_course_reaction_counts(bigint[]);
drop function if exists public.get_course_reaction_counts(bigint[], text);
create or replace function public.get_course_reaction_counts(course_ids bigint[], p_session_id text default null)
returns table(course_id bigint, likes bigint, dislikes bigint, user_reaction text)
language sql
security definer
set search_path = public
as $$
  select ids.course_id,
         (coalesce(max(c.initial_likes),0) + coalesce(sum(case when r.reaction = 'like' then 1 else 0 end),0))::bigint,
         (coalesce(max(c.initial_dislikes),0) + coalesce(sum(case when r.reaction = 'dislike' then 1 else 0 end),0))::bigint,
         (select cr.reaction from public.course_reactions cr where cr.course_id = ids.course_id and cr.session_id = p_session_id limit 1)
  from unnest(course_ids) as ids(course_id)
  left join public.course_catalogue c on c.id = ids.course_id
  left join public.course_reactions r on r.course_id = ids.course_id
  group by ids.course_id
  order by ids.course_id;
$$;
grant execute on function public.get_course_reaction_counts(bigint[], text) to anon;

create or replace function public.set_course_reaction(
  p_course_id bigint,
  p_session_id text,
  p_reaction text
)
returns table(course_id bigint, likes bigint, dislikes bigint, user_reaction text)
language plpgsql
security definer
set search_path = public
as $$
declare old_reaction text;
begin
  if p_reaction not in ('like','dislike') then raise exception 'invalid reaction'; end if;
  if length(p_session_id) < 12 or length(p_session_id) > 120 then raise exception 'invalid session'; end if;

  select reaction into old_reaction from public.course_reactions where course_id = p_course_id and session_id = p_session_id;
  if old_reaction = p_reaction then
    delete from public.course_reactions where course_id = p_course_id and session_id = p_session_id;
  else
    insert into public.course_reactions(course_id, session_id, reaction, updated_at)
    values (p_course_id, p_session_id, p_reaction, now())
    on conflict (course_id, session_id) do update set reaction = excluded.reaction, updated_at = now();
  end if;

  return query
  select p_course_id,
         (coalesce(c.initial_likes,0) + coalesce((select count(*) from public.course_reactions where course_id=p_course_id and reaction='like'),0))::bigint,
         (coalesce(c.initial_dislikes,0) + coalesce((select count(*) from public.course_reactions where course_id=p_course_id and reaction='dislike'),0))::bigint,
         (select reaction from public.course_reactions where course_id=p_course_id and session_id=p_session_id)
  from public.course_catalogue c where c.id=p_course_id;
end;
$$;
grant execute on function public.set_course_reaction(bigint, text, text) to anon;

create or replace function public.validate_coupon(p_code text, p_subtotal numeric)
returns table(status text, message text, discount_percent numeric, discount_amount numeric, total numeric, code text)
language plpgsql
security definer
set search_path = public
as $$
declare c public.coupons%rowtype;
declare clean_code text;
BEGIN
  clean_code := upper(trim(coalesce(p_code,'')));
  select * into c from public.coupons where upper(code) = clean_code limit 1;

  if c.id is null or c.is_active = false then
    return query select 'not_valid'::text, 'Coupon not valid'::text, 0::numeric, 0::numeric, greatest(coalesce(p_subtotal,0),0)::numeric, clean_code;
    return;
  end if;

  if c.starts_at is not null and now() < c.starts_at then
    return query select 'not_valid'::text, 'Coupon not active yet'::text, 0::numeric, 0::numeric, greatest(coalesce(p_subtotal,0),0)::numeric, clean_code;
    return;
  end if;

  if c.expires_at is not null and now() > c.expires_at then
    return query select 'expired'::text, 'Coupon expired'::text, c.discount_percent, 0::numeric, greatest(coalesce(p_subtotal,0),0)::numeric, upper(c.code);
    return;
  end if;

  return query select 'valid'::text,
    'Coupon applied'::text,
    c.discount_percent,
    round((greatest(coalesce(p_subtotal,0),0) * c.discount_percent / 100.0), 2),
    round(greatest(coalesce(p_subtotal,0),0) - (greatest(coalesce(p_subtotal,0),0) * c.discount_percent / 100.0), 2),
    upper(c.code);
END;
$$;
grant execute on function public.validate_coupon(text, numeric) to anon;

-- Seed 24 demo courses so the live database and UI start in sync.
insert into public.course_catalogue
(id, number, title, category, educator, price, rating, reviews, initial_likes, initial_dislikes, is_active, created_at)
values
(1,1,'Alpha Batch 3.0','Coding & Tech','Sayeed Courses',299,4.8,307,0,0,true,'2026-09-01T12:00:00+05:30'),
(2,2,'Complete DSA Batch','AI & Automation','Sayeed Courses',199,4.9,184,0,0,true,'2026-09-02T12:00:00+05:30'),
(3,3,'AI Automation Mastery','Finance & Taxation','Sayeed Courses',399,4.7,156,0,0,true,'2026-09-03T12:00:00+05:30'),
(4,4,'Personal Growth Blueprint','Personal Growth & Mindset','Sayeed Courses',249,4.6,212,0,0,true,'2026-09-04T12:00:00+05:30'),
(5,5,'Advanced Web Development','Coding & Tech','Sayeed Courses',299,4.5,142,0,0,true,'2026-09-05T12:00:00+05:30'),
(6,6,'Python Pro Bootcamp','AI & Automation','Sayeed Courses',199,4.8,230,0,0,true,'2026-09-06T12:00:00+05:30'),
(7,7,'UI/UX Design Mastery','Coding & Tech','Sayeed Courses',399,4.4,98,0,0,true,'2026-09-07T12:00:00+05:30'),
(8,8,'Digital Marketing Accelerator','Finance & Taxation','Sayeed Courses',249,4.9,321,0,0,true,'2026-09-08T12:00:00+05:30'),
(9,9,'Excel & Data Skills','Finance & Taxation','Sayeed Courses',299,4.3,145,0,0,true,'2026-09-09T12:00:00+05:30'),
(10,10,'No-Code Automation Lab','AI & Automation','Sayeed Courses',199,4.6,176,0,0,true,'2026-09-10T12:00:00+05:30'),
(11,11,'Freelancing Launchpad','Personal Growth & Mindset','Sayeed Courses',399,4.7,205,0,0,true,'2026-09-11T12:00:00+05:30'),
(12,12,'Communication Mastery','Personal Growth & Mindset','Sayeed Courses',249,4.5,188,0,0,true,'2026-09-12T12:00:00+05:30'),
(13,13,'JavaScript From Zero','Coding & Tech','Sayeed Courses',299,4.8,251,0,0,true,'2026-09-13T12:00:00+05:30'),
(14,14,'React Production Course','Coding & Tech','Sayeed Courses',199,4.9,310,0,0,true,'2026-09-14T12:00:00+05:30'),
(15,15,'AI Tools for Work','AI & Automation','Sayeed Courses',399,4.4,121,0,0,true,'2026-09-15T12:00:00+05:30'),
(16,16,'Personal Finance Essentials','Finance & Taxation','Sayeed Courses',249,4.6,144,0,0,true,'2026-09-16T12:00:00+05:30'),
(17,17,'Canva Content Studio','Video Editing & Media','Sayeed Courses',299,4.7,217,0,0,true,'2026-09-17T12:00:00+05:30'),
(18,18,'Video Editing Pro','Video Editing & Media','Sayeed Courses',199,4.8,192,0,0,true,'2026-09-18T12:00:00+05:30'),
(19,19,'Instagram Growth Lab','Communication & Languages','Sayeed Courses',399,4.5,135,0,0,true,'2026-09-19T12:00:00+05:30'),
(20,20,'Copywriting Essentials','Communication & Languages','Sayeed Courses',249,4.7,164,0,0,true,'2026-09-20T12:00:00+05:30'),
(21,21,'Astrology Foundations','Astrology & Occult','Sayeed Courses',299,4.2,87,0,0,true,'2026-09-21T12:00:00+05:30'),
(22,22,'Fitness Fundamentals','Fitness & Health','Sayeed Courses',199,4.6,102,0,0,true,'2026-09-22T12:00:00+05:30'),
(23,23,'Mindset Reset Program','Personal Growth & Mindset','Sayeed Courses',399,4.9,255,0,0,true,'2026-09-23T12:00:00+05:30'),
(24,24,'Career Growth Blueprint','Personal Growth & Mindset','Sayeed Courses',249,4.5,173,0,0,true,'2026-09-24T12:00:00+05:30')
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.course_catalogue','id'),
  coalesce((select max(id) from public.course_catalogue), 1),
  true
);

insert into public.notifications(title, body, type)
select 'Welcome to Sayeed Courses', 'New course updates and important announcements will appear here.', 'info'
where not exists (select 1 from public.notifications);

-- Enable Supabase Realtime for catalogue, reactions and notifications.
do $$ begin
  alter publication supabase_realtime add table public.course_catalogue;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.course_reactions;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null; end $$;
