-- Sayeed Courses live backend foundation
-- Run this in Supabase SQL Editor.

create table if not exists public.course_catalogue (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  educator text,
  price numeric(10,2) default 0,
  thumbnail_url text,
  telegram_url text,
  initial_likes bigint not null default 0,
  initial_dislikes bigint not null default 0,
  created_at timestamptz default now()
);

create table if not exists public.course_reactions (
  course_id bigint not null references public.course_catalogue(id) on delete cascade,
  session_id text not null,
  reaction text not null check (reaction in ('like','dislike')),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  primary key (course_id, session_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  type text default 'info',
  created_at timestamptz default now()
);

alter table public.course_catalogue enable row level security;
alter table public.course_reactions enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "public read course catalogue" on public.course_catalogue;
create policy "public read course catalogue" on public.course_catalogue for select to anon using (true);

drop policy if exists "public read notifications" on public.notifications;
create policy "public read notifications" on public.notifications for select to anon using (true);

create or replace function public.get_course_count()
returns bigint
language sql
security definer
set search_path = public
as $$ select count(*) from public.course_catalogue; $$;

grant execute on function public.get_course_count() to anon;

drop function if exists public.get_course_reaction_counts(bigint[]);
create or replace function public.get_course_reaction_counts(course_ids bigint[])
returns table(course_id bigint, likes bigint, dislikes bigint)
language sql
security definer
set search_path = public
as $$
  select ids.course_id,
         (coalesce(max(c.initial_likes),0) + coalesce(sum(case when r.reaction = 'like' then 1 else 0 end),0))::bigint,
         (coalesce(max(c.initial_dislikes),0) + coalesce(sum(case when r.reaction = 'dislike' then 1 else 0 end),0))::bigint
  from unnest(course_ids) as ids(course_id)
  left join public.course_catalogue c on c.id = ids.course_id
  left join public.course_reactions r on r.course_id = ids.course_id
  group by ids.course_id
  order by ids.course_id;
$$;

grant execute on function public.get_course_reaction_counts(bigint[]) to anon;

create or replace function public.set_course_reaction(
  p_course_id bigint,
  p_session_id text,
  p_reaction text
)
returns table(course_id bigint, likes bigint, dislikes bigint, user_reaction text)
language plpgsql
security definer
set search_path = public
as $$
declare old_reaction text;
begin
  if p_reaction not in ('like','dislike') then raise exception 'invalid reaction'; end if;
  if length(p_session_id) < 12 or length(p_session_id) > 120 then raise exception 'invalid session'; end if;

  select reaction into old_reaction from public.course_reactions where course_id = p_course_id and session_id = p_session_id;
  if old_reaction = p_reaction then
    delete from public.course_reactions where course_id = p_course_id and session_id = p_session_id;
  else
    insert into public.course_reactions(course_id, session_id, reaction, updated_at)
    values (p_course_id, p_session_id, p_reaction, now())
    on conflict (course_id, session_id) do update set reaction = excluded.reaction, updated_at = now();
  end if;

  return query
  select p_course_id,
         (coalesce(c.initial_likes,0) + coalesce((select count(*) from public.course_reactions where course_id=p_course_id and reaction='like'),0))::bigint,
         (coalesce(c.initial_dislikes,0) + coalesce((select count(*) from public.course_reactions where course_id=p_course_id and reaction='dislike'),0))::bigint,
         (select reaction from public.course_reactions where course_id=p_course_id and session_id=p_session_id)
  from public.course_catalogue c where c.id=p_course_id;
end;
$$;

grant execute on function public.set_course_reaction(bigint, text, text) to anon;

insert into public.notifications(title, body, type)
select 'Welcome to Sayeed Courses', 'New course updates and important announcements will appear here.', 'info'
where not exists (select 1 from public.notifications);
